version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_learning_app
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_learning_data:/data/db

volumes:
  mongodb_learning_data:
